import assert from 'node:assert/strict';
import { analyzeSamples, quantize, makeDemo, resizeTracks, exportMusicXML, scoreTaps } from './lib/music.ts';
const rate=16000, samples=new Float32Array(rate*3);
const times=[.2,.45,.95,1.7];
for(const t of times)for(let j=0;j<320;j++)samples[Math.floor(t*rate)+j]=.7*Math.exp(-j/60)*Math.cos(j*1.8);
const result=analyzeSamples(samples,rate,80,12);
assert.equal(result.onsets.length,times.length,'Isolated transients should be detected once each');
result.onsets.forEach((t,i)=>assert.ok(Math.abs(t-times[i])<.025,'onset time stays near recorded transient'));
assert.equal(result.duration,3);
assert.deepEqual(result.hits.map((v,i)=>v?i:-1).filter(i=>i>=0),[0,1,3,6]);
const silent=analyzeSamples(new Float32Array(rate),rate,96,12);
assert.equal(silent.onsets.length,0);
assert.ok(silent.envelope.every(Number.isFinite));
assert.deepEqual(quantize([.2,.45,.7,4],80,6),[true,true,true,false,false,false]);
const demo=makeDemo(),grown=resizeTracks(demo,16);
assert.deepEqual(grown[0].hits.slice(0,12),demo[0].hits);
assert.deepEqual(grown[0].hits.slice(12),[false,false,false,false]);
assert.equal(resizeTracks(demo,6)[0].hits.length,6);
const score=scoreTaps([0,.5,1],[.01,.49,.51,1.02],.1);
assert.equal(score.matches,3);assert.equal(score.extra,1);
assert.equal(scoreTaps([0,.5,1],[.01],.1).matches,1,'One tap cannot satisfy multiple targets');
const xml=exportMusicXML(demo,12,96,'Rhythm <study> & friends');
assert.ok(xml.includes('Rhythm &lt;study&gt; &amp; friends'));
assert.equal((xml.match(/<note>/g)||[]).length,36);
assert.equal((xml.match(/<rest\/>/g)||[]).length,demo.flatMap(t=>t.hits).filter(h=>!h).length);
assert.ok(xml.includes('<sound tempo="144"/>'),'Dotted-quarter BPM should export as quarter-note MIDI tempo');
console.log('PASS: isolated transient detection, silence, quantization, resizing, timing feedback, and MusicXML export');
