"use client";
import { useEffect, useRef, useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpRight, AudioLines, BookOpen, Check, CircleHelp, Compass, FileMusic, Grid2X2, Headphones, Layers3, LoaderCircle, Mic, Music2, Pause, Play, Plus, Radio, Search, Settings2, Sparkles, Square, Trash2, Upload, Volume2, X } from "lucide-react";
import { useNotebookTool } from "@/lib/use-notebook-tool";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { type Track, type RecordingAnalysis, analyzeSamples, exportMusicXML, makeDemo, quantize, resizeTracks, scheduleHit, scoreTaps } from "@/lib/music";
import { Staff, SourceCard, CitedText, type Citation, type Source, formatTime } from "@/components/music-views";
type FieldNote={id:string;text:string;time:number;source:"researcher"|"Astra"};
type ApiReply={error?:string;explanation:string;update:{bpm:number;steps:number;tracks:Track[]}|null;text:string;sources:Source[];citations:Citation[]};
type Notebook={title:string;bpm:number;steps:number;tracks:Track[];notes:FieldNote[];analysis:RecordingAnalysis|null;audio?:Blob};
export default function Home(){
  const [view,setView]=useState("notebook"),[notation,setNotation]=useState("grid"),[title,setTitle]=useState("A conversation in rhythm"),[tracks,setTracks]=useState<Track[]>(makeDemo),[steps,setSteps]=useState(12),[bpm,setBpm]=useState(96),[playing,setPlaying]=useState(false),[cursor,setCursor]=useState(-1),[note,setNote]=useState("");
  const [notes,setNotes]=useState<FieldNote[]>([{id:"intro",text:"Original practice sketch: two interlocking parts over a steady pulse. This synthetic example is not attributed to a musical tradition. Try changing a few cells, then listen to the relationship between the parts.",time:0,source:"researcher"}]);
  const [message,setMessage]=useState(""),[help,setHelp]=useState(false),[settings,setSettings]=useState(false),[key,setKey]=useState(""),[serverReady,setServerReady]=useState(false),[busy,setBusy]=useState(""),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[audioUrl,setAudioUrl]=useState(""),[analysis,setAnalysis]=useState<RecordingAnalysis|null>(null),[query,setQuery]=useState(""),[research,setResearch]=useState(""),[sources,setSources]=useState<Source[]>([]),[voiceRecording,setVoiceRecording]=useState(false),[saved,setSaved]=useState(false),[practice,setPractice]=useState(false),[taps,setTaps]=useState<number[]>([]),[practiceResult,setPracticeResult]=useState(""),[practiceTrack,setPracticeTrack]=useState(0),[sensitivity,setSensitivity]=useState(.018),[selectedTime,setSelectedTime]=useState(0);
  const audioRef=useRef<AudioContext|null>(null),mediaRef=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),voiceRef=useRef<MediaRecorder|null>(null),audioBlob=useRef<Blob|undefined>(undefined),fileRef=useRef<HTMLInputElement>(null),playTimer=useRef<ReturnType<typeof setInterval>|null>(null),scheduled=useRef<ReturnType<typeof setTimeout>[]>([]),practiceStart=useRef(0),tapRef=useRef<number[]>([]),notebookRef=useRef<Notebook|null>(null);
  const soundNodes=useRef<OscillatorNode[]>([]);
  useNotebookTool(notebookRef);
  const [citations,setCitations]=useState<Citation[]>([]);
  const ready=serverReady||!!key;
  async function context(){if(!audioRef.current)audioRef.current=new AudioContext();await audioRef.current.resume();return audioRef.current;}
  function stopPlayback(){soundNodes.current.forEach(n=>{try{n.stop();n.disconnect();}catch{}});soundNodes.current=[];if(playTimer.current)clearInterval(playTimer.current);scheduled.current.forEach(clearTimeout);scheduled.current=[];setPlaying(false);setCursor(-1);}
  async function togglePlayback(){if(playing){stopPlayback();return;}const ctx=await context();setPlaying(true);let next=ctx.currentTime+.07,step=0;const tick=()=>{while(next<ctx.currentTime+.12){const s=step%steps;tracks.forEach((t,i)=>{if(!t.muted&&t.hits[s])soundNodes.current.push(scheduleHit(ctx,next,i));});scheduled.current.push(setTimeout(()=>setCursor(s),Math.max(0,(next-ctx.currentTime)*1000)));next+=60/bpm/3;step++;}};tick();playTimer.current=setInterval(tick,25);}
  useEffect(()=>{stopPlayback();setPracticeTrack(i=>Math.min(i,tracks.length-1));},[steps,bpm,tracks]);
  useEffect(()=>()=>{if(playTimer.current)clearInterval(playTimer.current);scheduled.current.forEach(clearTimeout);streamRef.current?.getTracks().forEach(t=>t.stop());void audioRef.current?.close();},[]);
  useEffect(()=>{if(!recording&&!voiceRecording)return;const start=Date.now(),t=setInterval(()=>setElapsed((Date.now()-start)/1000),100);return()=>clearInterval(t);},[recording,voiceRecording]);
  useEffect(()=>{if(elapsed>=60&&recording)mediaRef.current?.stop();if(elapsed>=60&&voiceRecording)voiceRef.current?.stop();},[elapsed,recording,voiceRecording]);
  useEffect(()=>{if(audioUrl)return()=>URL.revokeObjectURL(audioUrl);},[audioUrl]);
  useEffect(()=>{fetch("/api/astra").then(r=>r.json() as Promise<{configured:boolean}>).then(d=>setServerReady(!!d.configured)).catch(()=>{});},[]);
  useEffect(()=>{notebookRef.current={title,bpm,steps,tracks,notes,analysis,audio:audioBlob.current};setSaved(false);},[title,bpm,steps,tracks,notes,analysis]);
  function changeSteps(n:number){setSteps(n);setTracks(t=>resizeTracks(t,n));}
  function changeHit(row:number,col:number){setTracks(t=>t.map((v,i)=>i===row?{...v,hits:v.hits.map((h,j)=>j===col?!h:h)}:v));}
  function addNote(text=note,source:FieldNote["source"]="researcher"){if(!text.trim())return;setNotes(n=>[...n,{id:crypto.randomUUID(),text:text.trim(),time:selectedTime,source}]);if(source==="researcher")setNote("");}
  function loadDemo(){stopPlayback();setTitle("A conversation in rhythm");setTracks(makeDemo());setSteps(12);setBpm(96);setAnalysis(null);setAudioUrl("");audioBlob.current=undefined;setNotes([{id:crypto.randomUUID(),text:"Original practice sketch, synthesized in the browser. No cultural origin is inferred. Part 1 and Part 2 interlock over a steady pulse.",time:0,source:"researcher"}]);setMessage("Practice sketch loaded. Every cell is editable.");}
  async function analyzeBlob(blob:Blob,name:string){setBusy("Finding sound events…");try{const ctx=await context(),buffer=await ctx.decodeAudioData(await blob.arrayBuffer());if(buffer.duration>60)throw Error("Please use a recording of 60 seconds or less.");const samples=new Float32Array(buffer.length);for(let c=0;c<buffer.numberOfChannels;c++){const data=buffer.getChannelData(c);for(let i=0;i<data.length;i++)samples[i]+=data[i]/buffer.numberOfChannels;}const result=analyzeSamples(samples,buffer.sampleRate,bpm,steps,sensitivity);audioBlob.current=blob;setAudioUrl(URL.createObjectURL(blob));setAnalysis(result);setTracks([{name:"Detected events",color:"orange",hits:result.hits,muted:false}]);setTitle(name);setSelectedTime(0);setNotes([]);setMessage(result.onsets.length?`${result.onsets.length} sound events found. Review tempo and cycle length; the grid shows the first cycle.`:"No clear onsets found. Try a louder isolated pattern or lower the detection threshold.");}catch(e){setMessage(e instanceof Error?e.message:"This audio format could not be decoded. Try WAV or MP3.");}finally{setBusy("");}}
  async function startRecording(){try{stopPlayback();const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});streamRef.current=stream;const recorder=new MediaRecorder(stream),chunks:Blob[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);void analyzeBlob(new Blob(chunks,{type:recorder.mimeType}),"Untitled field recording");};mediaRef.current=recorder;setElapsed(0);setRecording(true);recorder.start();setMessage("Recording up to 60 seconds. Isolated clapping or a single instrument gives a clearer draft.");}catch{setMessage("Microphone unavailable. Allow access in your browser, or upload an audio file.");}}
  async function api(action:string,payload:Record<string,unknown>){const r=await fetch("/api/astra",{method:"POST",headers:{"Content-Type":"application/json",...(key?{"Authorization":`Bearer ${key}`}:{})},body:JSON.stringify({action,...payload})});const d=await r.json() as ApiReply;if(!r.ok)throw Error(d.error||"Astra could not complete this request.");return d;}
  async function askAstra(){if(!ready){setSettings(true);return;}setBusy("Astra is reading your notebook…");try{const originalPattern=JSON.stringify({bpm,steps,tracks});const d=await api("interpret",{instruction:note||"Explain this rhythm and suggest a focused listening exercise. Only change the pattern if asked.",notebook:{title,bpm,steps,tracks,notes,analysis}});if(note)addNote();addNote(d.explanation,"Astra");if(d.update){const current=notebookRef.current;if(current&&JSON.stringify({bpm:current.bpm,steps:current.steps,tracks:current.tracks})===originalPattern){setBpm(d.update.bpm);setSteps(d.update.steps);setTracks(d.update.tracks);}else addNote("The pattern changed while Astra was working, so its proposed edit was not applied. Ask again to update the current version.","Astra");}setMessage("Astra’s interpretation is added to your field notes.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}}
  async function findPerformances(){if(!query.trim()){setMessage("Enter a musician, instrument, tradition, or question.");return;}if(!ready){setSettings(true);return;}setBusy("Searching for performances and their context…");try{const d=await api("search",{query,context:notes.filter(n=>n.source==="researcher").map(n=>n.text).join("\n")});setResearch(d.text);setSources(d.sources);setCitations(d.citations||[]);setMessage(d.sources.length?"Search complete. Open the sources to assess each connection.":"No cited sources returned. Try a more specific name.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}}
  async function voiceNote(){if(voiceRecording){voiceRef.current?.stop();return;}if(!ready){setSettings(true);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const recorder=new MediaRecorder(stream),chunks:Blob[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setVoiceRecording(false);setBusy("Transcribing your field note…");try{const form=new FormData();form.append("file",new Blob(chunks,{type:recorder.mimeType}),`field-note.${recorder.mimeType.includes("mp4")?"mp4":"webm"}`);const r=await fetch("/api/transcribe",{method:"POST",headers:key?{"Authorization":`Bearer ${key}`}:{},body:form});const d=await r.json() as ApiReply;if(!r.ok)throw Error(d.error||"The request failed.");setNote(n=>(n?n+"\n":"")+d.text);setMessage("Spoken note transcribed. Review it, then save or ask Astra.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}};voiceRef.current=recorder;setElapsed(0);setVoiceRecording(true);recorder.start();}catch{setMessage("Microphone unavailable. You can type your field note instead.");}}
  async function saveNotebook(){try{const {saveLocal}=await import("@/lib/storage");await saveLocal({...notebookRef.current!,audio:audioBlob.current});setSaved(true);setMessage("Notebook and recording saved on this device.");}catch{setMessage("Device storage unavailable. Export your notebook to keep a copy.");}}
  async function openNotebook(){try{const {loadLocal}=await import("@/lib/storage");const n=await loadLocal() as Notebook|undefined;if(!n){setMessage("No saved notebook on this device yet.");return;}stopPlayback();setTitle(n.title);setBpm(n.bpm);setSteps(n.steps);setTracks(n.tracks);setNotes(n.notes);setAnalysis(n.analysis);setSelectedTime(0);audioBlob.current=n.audio;setAudioUrl(n.audio?URL.createObjectURL(n.audio):"");setMessage("Saved notebook opened.");}catch{setMessage("Could not open device storage.");}}
  function download(data:Blob|string,name:string,type="application/json"){const u=URL.createObjectURL(typeof data==="string"?new Blob([data],{type}):data),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  async function startPractice(){stopPlayback();await context();setTaps([]);tapRef.current=[];setPracticeResult("");practiceStart.current=performance.now()+1000;setPractice(true);setMessage("One second to get ready. Tap the pad to play the selected part for two cycles.");}
  function tap(){if(!practice)return;const t=(performance.now()-practiceStart.current)/1000;if(t<0)return;tapRef.current.push(t);setTaps([...tapRef.current]);if(audioRef.current)scheduleHit(audioRef.current,audioRef.current.currentTime,practiceTrack);}
  useEffect(()=>{if(!practice)return;const ctx=audioRef.current!,startAudio=ctx.currentTime+1,duration=60/bpm/3;for(let i=0;i<steps*2;i++){if(i%3===0)soundNodes.current.push(scheduleHit(ctx,startAudio+i*duration,2));scheduled.current.push(setTimeout(()=>setCursor(i%steps),1000+i*duration*1000));}const timer=setTimeout(()=>{setPractice(false);setCursor(-1);const target=tracks[practiceTrack].hits.flatMap((h,i)=>h?[i*duration,(i+steps)*duration]:[]),score=scoreTaps(target,tapRef.current,duration*.45);setPracticeResult(target.length?`${score.matches} of ${target.length} target sounds matched${score.matches?`, averaging ${score.averageMs} ms from the grid`:""}. ${score.extra} extra taps. ${score.matches===target.length&&!score.extra?"Try bringing in another part.":"Listen again and focus on the spaces between sounds."}`:"Add sound events to this part before practicing.");},1000+steps*2*duration*1000+150);return()=>clearTimeout(timer);},[practice]);
  useEffect(()=>{if(!practice)return;const listener=(e:KeyboardEvent)=>{if(e.code==="Space"&&!e.repeat&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();tap();}};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);},[practice]);
  return <Tabs value={view} onValueChange={v=>{stopPlayback();setPractice(false);setView(v);}} className="app-root">
    <header className="topbar"><a className="brand" href="/" aria-label="Common Pulse home"><span className="brand-symbol"><AudioLines size={23}/></span><span>common<span className="brand-light">pulse</span><span className="brand-dot">.</span></span></a><TabsList className="main-nav" variant="line"><TabsTrigger value="notebook"><BookOpen/>Field notebook</TabsTrigger><TabsTrigger value="discover"><Compass/>Discover</TabsTrigger><TabsTrigger value="practice"><Headphones/>Practice</TabsTrigger></TabsList><div className="header-actions"><button className="astra-status" onClick={()=>setSettings(true)}><Sparkles size={14}/>{ready?"Astra enabled":"Connect Astra"}</button><button className="icon-button" aria-label="How Common Pulse works" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button></div></header>
    <div className="workspace"><div className="breadcrumb"><span>YOUR WORKSPACE</span><span>/</span><span>{view==="notebook"?"Field notebook":view==="discover"?"Performance discovery":"Practice room"}</span><span className="local-label">Private · device-local notebook</span></div>
    <TabsContent value="notebook" className="page-content"><div className="page-heading"><div><div className="eyebrow">LISTEN CLOSELY. KEEP THE CONTEXT.</div><input className="title-input" aria-label="Notebook title" value={title} onChange={e=>setTitle(e.target.value)}/><p className="subline">A space for sound, notation, and the stories around them.</p></div><div className="heading-actions"><Button variant="outline" onClick={openNotebook} disabled={recording||!!busy}><BookOpen/>Open saved</Button><Button onClick={saveNotebook}>{saved?<Check/>:<Plus/>}{saved?"Saved":"Save notebook"}</Button></div></div>
    <div className="notebook-layout"><div className="primary-column"><section className="recording-panel"><div className="section-top"><div className="section-label"><Radio size={16}/>THE RECORDING</div><span className="small-tag">{audioUrl?"Your recording":"Synthetic practice sketch"}</span></div><div className="waveform" aria-label={analysis?"Recorded audio amplitude":"Illustrative waveform for practice sketch"}>{Array.from({length:100},(_,i)=><span key={i} style={{height:`${analysis?Math.max(3,(analysis.envelope[i]||0)*100):8+Math.abs(Math.sin(i*2.3)*Math.cos(i*.31))*64}%`}}/>)}<div className="waveform-line"/></div><div className="wave-axis"><span>00:00</span><span>{audioUrl?formatTime((analysis?.duration||0)/2):"ORIGINAL RHYTHM STUDY"}</span><span>{analysis?formatTime(analysis.duration):"12 PULSES"}</span></div>{audioUrl&&<audio className="recorded-audio" controls src={audioUrl} onTimeUpdate={e=>setSelectedTime(e.currentTarget.currentTime)}/>}
    <div className="record-controls"><div className="inline-controls"><Button className={recording?"record-btn is-recording":"record-btn"} onClick={()=>recording?mediaRef.current?.stop():startRecording()} disabled={!!busy||voiceRecording}>{recording?<Square/>:<Mic/>}{recording?`Stop · ${formatTime(elapsed)}`:"Record sound"}</Button><Button variant="ghost" disabled={recording||!!busy||voiceRecording} onClick={()=>fileRef.current?.click()}><Upload/>Upload</Button><input ref={fileRef} type="file" accept="audio/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>20*1024*1024)setMessage("Choose an audio file smaller than 20 MB.");else void analyzeBlob(f,f.name.replace(/\.[^.]+$/,""));}e.target.value="";}}/></div><button className="text-button" onClick={loadDemo} disabled={recording||!!busy}>Try a practice sketch <ArrowUpRight size={15}/></button></div></section>
    <section className="notation-panel"><Tabs value={notation} onValueChange={setNotation}><div className="notation-header"><TabsList className="notation-tabs" variant="line"><TabsTrigger value="grid"><Grid2X2/>TUBS grid</TabsTrigger><TabsTrigger value="staff"><FileMusic/>Staff notation</TabsTrigger><TabsTrigger value="structure"><Layers3/>Structure</TabsTrigger></TabsList><span className="draft-tag">Editable draft</span></div><div className="notation-toolbar"><div className="inline-controls"><label className="compact-field">Cycle <select value={steps} onChange={e=>changeSteps(+e.target.value)}>{[6,8,9,12,16,24].map(n=><option key={n} value={n}>{n} pulses</option>)}</select></label><span className="toolbar-divider"/><label className="compact-field"><input aria-label="Tempo in beats per minute" type="number" min={30} max={240} value={bpm} onChange={e=>setBpm(Math.max(30,Math.min(240,+e.target.value||30)))}/>BPM</label></div><span className="notation-hint">3 pulses / beat</span></div>
    <TabsContent value="grid"><div className="grid-scroll"><div className="tubs-grid" style={{gridTemplateColumns:`150px repeat(${steps},minmax(26px,1fr))`}}><div className="grid-caption">PART / PULSE</div>{Array.from({length:steps},(_,i)=><span key={i} className={`pulse-number ${i===cursor?"current":""}`}>{String(i+1).padStart(2,"0")}</span>)}{tracks.map((track,row)=><div className="grid-row" key={row}><div className="track-name"><button aria-label={`${track.muted?"Unmute":"Mute"} ${track.name}`} onClick={()=>setTracks(t=>t.map((v,i)=>i===row?{...v,muted:!v.muted}:v))} className={track.muted?"muted":""}><Volume2 size={15}/></button><input aria-label={`Part ${row+1} name`} value={track.name} onChange={e=>setTracks(t=>t.map((v,i)=>i===row?{...v,name:e.target.value}:v))}/></div>{track.hits.map((hit,col)=><button key={col} className={`tubs-cell ${track.color} ${hit?"hit":""} ${col===cursor?"playhead":""} ${col%3===0?"beat-start":""}`} aria-label={`${track.name}, pulse ${col+1}`} aria-pressed={hit} onClick={()=>changeHit(row,col)}>{hit?(row===2?<span className="pulse-dot"/>:<X size={19} strokeWidth={2.5}/>):<span className="empty-dot"/>}</button>)}</div>)}</div></div><div className="grid-footer"><button className="text-button" disabled={tracks.length>=6} onClick={()=>setTracks(t=>[...t,{name:`Part ${t.length+1}`,color:["orange","blue","slate"][t.length%3],hits:Array(steps).fill(false),muted:false}])}><Plus size={14}/>Add part</button><span>Click a box to add or remove a sound.</span></div>{analysis&&<button className="requantize text-button" onClick={()=>{setTracks(t=>t.map((v,i)=>i===0?{...v,hits:quantize(analysis.onsets,bpm,steps)}:v));setMessage("First part regenerated from original onsets at the current tempo and cycle length.");}}>Rebuild first part from recording</button>}</TabsContent>
    <TabsContent value="staff"><Staff tracks={tracks} steps={steps}/><div className="grid-footer"><span>Rhythmic staff · one eighth note or rest per pulse</span><button className="text-button" onClick={()=>download(exportMusicXML(tracks,steps,bpm,title),"common-pulse.musicxml","application/vnd.recordare.musicxml+xml")}><ArrowDownToLine size={14}/>MusicXML</button></div></TabsContent>
    <TabsContent value="structure"><div className="structure-view"><div className="section-top"><h3>Sound over time</h3><span className="small-tag">{analysis?"Energy-based candidates":"Practice sketch"}</span></div>{analysis?<><p>Candidate boundaries follow changes in energy. Listen and annotate their musical meaning.</p><div className="segment-bar">{analysis.sections.map((s,i)=><button key={i} style={{flex:s.end-s.start}} onClick={()=>{setSelectedTime(s.start);setNote(`At ${formatTime(s.start)}: `);}} title={`${formatTime(s.start)}–${formatTime(s.end)}`}>{String.fromCharCode(65+i)}</button>)}</div>{analysis.sections.map((s,i)=><div className="section-entry" key={i}><b>{String.fromCharCode(65+i)}</b><span>{formatTime(s.start)} – {formatTime(s.end)}</span><span>{s.label}</span></div>)}</>:<><div className="segment-bar"><span>Cycle 1</span><span>Cycle 2</span><span>Cycle 3</span><span>Cycle 4</span></div><p>Record a performance to see candidate section boundaries and time-linked observations.</p></>}</div></TabsContent>
    <div className="transport"><Button className="play-button" onClick={togglePlayback} disabled={recording||practice}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}{playing?"Pause":"Listen to pattern"}</Button><div className="transport-caption"><span>{steps}-pulse cycle</span><span>Looped synthesized playback</span></div><span className="transport-icon"><AudioLines size={29}/></span></div></Tabs></section>
    <section className="instrument-panel"><div className="section-top"><h3><Music2 size={18}/>Sound sources</h3><span className="small-tag">Researcher labels</span></div><div className="instrument-tags">{tracks.map((t,i)=><span key={i}><span className={`source-dot ${t.color}`}/>{t.name}</span>)}</div><p>{analysis?"Audio detection finds onsets, not instrument identities. Name each part using your observations; ask Astra to help interpret your notes.":"Rename the parts above as you learn what makes each sound."}</p></section></div>
    <aside className="notes-panel"><div className="notes-heading"><span className="note-icon"><BookOpen size={20}/></span><div><h2>The field notebook</h2><p>Keep the people with the music.</p></div></div><div className="notes-list">{notes.map(n=><article className={`field-note ${n.source==="Astra"?"astra-note":""}`} key={n.id}><div className="note-meta"><span>{n.source==="Astra"?<Sparkles size={12}/>:<span className="note-dot"/>}{n.source==="Astra"?"ASTRA · INTERPRETATION":"FIELD NOTE"}</span><time>{formatTime(n.time)}</time></div><p>{n.text}</p><button className="delete-note" aria-label="Delete note" onClick={()=>setNotes(ns=>ns.filter(v=>v.id!==n.id))}><Trash2 size={12}/></button></article>)}</div><div className="note-composer"><label htmlFor="field-note">What are you hearing?</label><textarea id="field-note" value={note} onChange={e=>setNote(e.target.value)} placeholder={'“The bell marks the beginning of each cycle…”'} rows={4}/><div className="composer-tools"><button className={`text-button ${voiceRecording?"recording-text":""}`} onClick={voiceNote} disabled={recording||!!busy}>{voiceRecording?<Square size={15}/>:<Mic size={15}/>} {voiceRecording?`Stop ${formatTime(elapsed)}`:"Speak a note"}</button><button className="text-button" onClick={()=>addNote()} disabled={!note.trim()}>Save note <Plus size={14}/></button></div><Button className="ask-astra" variant="outline" onClick={askAstra} disabled={!!busy||recording||voiceRecording}><Sparkles/>{busy.startsWith("Astra")?"Thinking…":"Interpret with Astra"}<ArrowUpRight/></Button><p className="composer-hint">Describe context, ask a question, or request a correction to the pattern.</p></div><div className="context-card"><Compass size={19}/><div><strong>Follow the music further</strong><p>Find performances, musicians, and context beyond this recording.</p><button className="text-button" onClick={()=>{setView("discover");stopPlayback();}}>Explore performances <ArrowUpRight size={14}/></button></div></div></aside></div></TabsContent>
    <TabsContent value="discover" className="page-content"><div className="page-heading"><div><div className="eyebrow">MUSIC IN THE WORLD</div><h1>Follow the sound.</h1><p className="subline">Find the people and performances behind your questions.</p></div><Compass className="page-mark" size={60}/></div><div className="discover-layout"><section className="discovery-main"><form className="search-box" onSubmit={e=>{e.preventDefault();void findPerformances();}}><Search size={22}/><input aria-label="Search performances" value={query} onChange={e=>setQuery(e.target.value)} placeholder="A musician, instrument, tradition, or question…"/><Button disabled={!!busy} type="submit"><Sparkles/>Find with Astra</Button></form><div className="search-suggestions">Try a starting point:{["Carnatic konnakol demonstration","flamenco palmas tutorial","Ghana Ewe drumming ensemble"].map(q=><button key={q} onClick={()=>setQuery(q)}>{q}<ArrowUpRight size={12}/></button>)}</div>{research?<div className="research-result"><div className="section-label"><Sparkles size={16}/>ASTRA’S SEARCH NOTES</div><CitedText text={research} citations={citations}/><div className="sources-grid">{sources.map((s,i)=><SourceCard key={i} source={s}/>)}</div></div>:<div className="discovery-empty"><span className="discovery-orbit"><Radio size={40}/></span><h2>Every pattern has a context.</h2><p>Search with a specific name or a question. Astra brings back cited sources so you can explore and assess each connection yourself.</p></div>}</section><aside className="discovery-aside"><h3>Ways to listen</h3>{[["Meet the performers","Look for names, community sources, and the setting of a performance."],["Compare with care","A similar rhythm is an invitation to investigate, not proof of a shared origin."],["Bring it back","Add what you learn to the notebook in your own words."]].map(([h,p],i)=><div key={h}><b>0{i+1}</b><h4>{h}</h4><p>{p}</p></div>)}<a className="youtube-link" href={`https://www.youtube.com/results?search_query=${encodeURIComponent(query||"world music percussion demonstration")}`} target="_blank" rel="noreferrer">Search directly on YouTube <ArrowUpRight size={16}/></a></aside></div></TabsContent>
    <TabsContent value="practice" className="page-content"><div className="page-heading"><div><div className="eyebrow">YOUR HANDS ARE AN INSTRUMENT</div><h1>Find your part.</h1><p className="subline">Listen, leave space, and join the pattern from your notebook.</p></div></div><section className="practice-room"><div className="practice-settings"><label>Choose your part <select disabled={practice} value={practiceTrack} onChange={e=>setPracticeTrack(+e.target.value)}>{tracks.map((t,i)=><option key={i} value={i}>{t.name}</option>)}</select></label><span>{bpm} BPM · {steps} pulses · two cycles</span><Button variant="outline" disabled={practice} onClick={togglePlayback}>{playing?<Pause/>:<Headphones/>}{playing?"Stop listening":"Listen first"}</Button></div><div className="practice-pattern">{tracks[Math.min(practiceTrack,tracks.length-1)].hits.map((v,i)=><span key={i} className={`${v?"active":""} ${i===cursor?"current":""}`}>{v?"×":"·"}</span>)}</div><button className={`tap-pad ${practice?"live":""}`} onPointerDown={e=>{e.preventDefault();tap();}} aria-label="Tap your rhythm" disabled={!practice}><span>{practice?<Activity size={42}/>:<AudioLines size={42}/>}</span><strong>{practice?"Tap your part":"Ready when you are."}</strong><small>{practice?`${taps.length} sounds · or press space`:"Follow the pattern. Make room for the rests."}</small></button><Button className="practice-start" onClick={startPractice} disabled={practice}>{practice?<LoaderCircle className="spin"/>:<Play/>}{practice?"Listening to your taps…":"Start a two-cycle practice"}</Button>{practiceResult&&<p className="practice-feedback" role="status">{practiceResult}</p>}<p className="practice-explainer">Timing feedback compares your taps with the edited grid. You can also clap or vocalize your part using Record sound in the notebook.</p></section></TabsContent>
    <footer className="workspace-footer"><span><AudioLines size={14}/>Listen. Document. Participate.</span><div><button onClick={()=>download(JSON.stringify({...notebookRef.current,audio:undefined},null,2),"common-pulse-notebook.json")}><ArrowDownToLine size={14}/>Export notebook</button>{audioUrl&&<button onClick={()=>audioBlob.current&&download(audioBlob.current,"common-pulse-recording."+(audioBlob.current.type.includes("mp4")?"mp4":audioBlob.current.type.includes("wav")?"wav":audioBlob.current.type.includes("mpeg")?"mp3":"webm"))}>Download recording</button>}<button onClick={()=>setSettings(true)}><Settings2 size={14}/>Settings</button></div></footer></div>
    {(message||busy)&&<div className={`status-message ${busy?"busy":""}`} role="status">{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}<span>{busy||message}</span>{!busy&&<button aria-label="Dismiss status" onClick={()=>setMessage("")}><X size={16}/></button>}</div>}
    <Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogHeader><DialogTitle>Connect your research companion</DialogTitle><DialogDescription>Recording, grid editing, playback, and practice work without a connection. Astra adds interpretation and cited web discovery.</DialogDescription></DialogHeader><label className="settings-label">OpenAI API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value.trim())} placeholder="sk-…"/></label><p className="settings-copy">Your key stays in this tab’s memory and is sent through this app’s server to OpenAI for your requests. It is not saved with your notebook. API usage is billed to your OpenAI account.</p>{serverReady&&<p className="settings-copy">A server connection is already configured.</p>}<label className="settings-label">Sound detection threshold<input type="range" min="0.003" max="0.06" step="0.001" value={sensitivity} onChange={e=>setSensitivity(+e.target.value)}/><span className="settings-copy">Lower values pick up quieter sounds. Re-upload or record again to apply.</span></label><Button onClick={()=>{setSettings(false);setMessage(key?"Key added for this tab. Your next Astra request will verify access.":"Settings updated.");}}>Done</Button></DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>A notebook you can play</DialogTitle><DialogDescription>Start with the synthetic sketch, or record up to 60 seconds of your own music.</DialogDescription></DialogHeader><div className="help-copy"><p><b>1. Listen and record.</b> Isolated clapping or a single instrument gives the clearest rhythmic draft. Audio analysis runs on your device.</p><p><b>2. Edit the interpretation.</b> Each TUBS box is one equal pulse. Change tempo, cycle length, sound events, and part names. Staff notation shows the same rhythm.</p><p><b>3. Keep the context.</b> Add time-linked observations. With a key, spoken notes go to OpenAI for transcription; notes and sound measurements are sent when you ask Astra.</p><p><b>4. Participate.</b> Find cited performances or practice a part with the tap pad. Save on this device and export for safekeeping.</p><p>Automatic drafts do not establish cultural origin or identify instruments. Full pitched ensemble transcription is outside this prototype.</p></div></DialogContent></Dialog>
  </Tabs>;
}
