"use client";
import { ArrowUpRight } from "lucide-react";
import type { Track } from "@/lib/music";
export type Citation={start:number;end:number;url:string;title:string};
export function CitedText({text,citations}:{text:string;citations:Citation[]}){const nodes:React.ReactNode[]=[];let offset=0;for(const [i,c] of [...citations].sort((a,b)=>a.start-b.start).entries()){if(c.start<offset||c.end>text.length||c.start<0||c.end<=c.start)continue;nodes.push(text.slice(offset,c.start));nodes.push(<a key={i} href={c.url} target="_blank" rel="noreferrer" className="inline-citation" title={c.title}>[{i+1}] {c.title}</a>);offset=c.end;}nodes.push(text.slice(offset));return <p>{nodes}</p>;}
export function Staff({tracks,steps}:{tracks:Track[];steps:number}){const w=Math.max(700,steps*38+150);return <div className="staff-scroll"><svg className="staff" viewBox={`0 0 ${w} ${tracks.length*110+20}`} role="img" aria-label="Rhythmic staff notation; eighth notes mark sound events and eighth rests mark empty pulses">{tracks.map((t,row)=><g key={row} transform={`translate(0,${row*110})`}><text x="20" y="23" fontSize="14" fill="#59636e">{t.name}</text>{[0,1,2,3,4].map(i=><line key={i} x1="20" y1={40+i*8} x2={w-20} y2={40+i*8} stroke="#aab1b8" strokeWidth=".7"/>)}<path d="M34 45V67 M40 45V67" stroke="#293742" strokeWidth="3"/><text x="52" y="53" fontSize="14">{steps}</text><text x="55" y="70" fontSize="14">8</text>{t.hits.map((hit,i)=>{const x=92+i*(w-130)/steps;return <g key={i}>{hit?<><ellipse cx={x} cy="64" rx="5" ry="3.4" transform={`rotate(-20 ${x} 64)`} fill="#293742"/><line x1={x+4} x2={x+4} y1="63" y2="35" stroke="#293742" strokeWidth="1.4"/><path d={`M${x+4} 35 Q${x+17} 43 ${x+8} 52`} fill="none" stroke="#293742" strokeWidth="2"/></>:<><circle cx={x+3} cy="51" r="2.6" fill="#293742"/><path d={`M${x+3} 53 L${x+10} 47 L${x+4} 68`} fill="none" stroke="#293742" strokeWidth="1.8"/></>}<text x={x} y="94" textAnchor="middle" fontSize="12" fill="#87909a">{i+1}</text></g>;})}<line x1={w-21} x2={w-21} y1="40" y2="72" stroke="#293742" strokeWidth="2"/></g>)}</svg></div>;}
export type Source={title:string;url:string};
export function SourceCard({source}:{source:Source}){let videoId="";try{const url=new URL(source.url);if(url.hostname==="youtu.be")videoId=url.pathname.slice(1);if(["www.youtube.com","youtube.com","m.youtube.com"].includes(url.hostname))videoId=url.searchParams.get("v")||url.pathname.match(/^\/(?:shorts|embed)\/([\w-]+)/)?.[1]||"";}catch{}return <article className="source-card">{videoId&&/^[\w-]{11}$/.test(videoId)&&<iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={source.title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>}<a href={source.url} target="_blank" rel="noreferrer"><span>{source.title}</span><ArrowUpRight size={16}/></a><p>{videoId?"YouTube performance · verify context with the uploader":"Research source · open to review"}</p></article>;}
export function formatTime(n:number){return `${Math.floor(n/60).toString().padStart(2,"0")}:${Math.floor(n%60).toString().padStart(2,"0")}`;}
