import { z } from "zod";
export const trackSchema=z.object({name:z.string().min(1).max(100),color:z.enum(["orange","blue","slate"]),hits:z.array(z.boolean()).min(1).max(24),muted:z.boolean()});
export const updateSchema=z.object({bpm:z.number().min(30).max(240),steps:z.union([z.literal(6),z.literal(8),z.literal(9),z.literal(12),z.literal(16),z.literal(24)]),tracks:z.array(trackSchema).min(1).max(6)}).refine(v=>v.tracks.every(t=>t.hits.length===v.steps),"All parts must match the cycle length");
export const interpretationSchema=z.object({explanation:z.string().min(1).max(12000),update:updateSchema.nullable()});
export const responseSchema={type:"object",additionalProperties:false,properties:{explanation:{type:"string"},update:{anyOf:[{type:"null"},{type:"object",additionalProperties:false,properties:{bpm:{type:"number",minimum:30,maximum:240},steps:{type:"integer",enum:[6,8,9,12,16,24]},tracks:{type:"array",minItems:1,maxItems:6,items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},color:{type:"string",enum:["orange","blue","slate"]},hits:{type:"array",items:{type:"boolean"},minItems:1,maxItems:24},muted:{type:"boolean"}},required:["name","color","hits","muted"]}}},required:["bpm","steps","tracks"]}]}},required:["explanation","update"]};
export function getKey(request:Request){const key=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"";if(!key||key.length<20||key.length>500)throw new ApiError("Add your OpenAI API key in Settings to use Astra.",401);return key;}
export class ApiError extends Error{constructor(message:string,public status=400){super(message);}}
export function checkOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new ApiError("This request must come from Common Pulse.",403);}
export function safeUrl(value:unknown){if(typeof value!=="string")return null;try{const u=new URL(value);return u.protocol==="https:"||u.protocol==="http:"?u.href:null;}catch{return null;}}
export type Citation={start:number;end:number;url:string;title:string};
export function extractOutput(result:Record<string,unknown>){let text="";const citations:Citation[]=[];const sources:{title:string;url:string}[]=[];const output=Array.isArray(result.output)?result.output:[];
  for(const item of output){if(item.type!=="message"||!Array.isArray(item.content))continue;for(const part of item.content){if(part.type==="refusal")throw new ApiError("Astra could not help with that request. Try a different question.",422);if(part.type!=="output_text"||typeof part.text!=="string")continue;const offset=text.length;text+=part.text+"\n";for(const a of part.annotations||[]){const url=safeUrl(a.url);if(a.type!=="url_citation"||!url)continue;const title=typeof a.title==="string"?a.title:new URL(url).hostname;if(Number.isInteger(a.start_index)&&Number.isInteger(a.end_index)&&a.start_index>=0&&a.end_index<=part.text.length&&a.end_index>a.start_index)citations.push({start:offset+a.start_index,end:offset+a.end_index,url,title});if(!sources.some(s=>s.url===url))sources.push({title,url});}}}
  return {text:text.trimEnd(),citations,sources};
}
export async function openai(path:string,key:string,body:BodyInit,contentType?:string){const response=await fetch(`https://api.openai.com/v1/${path}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,...(contentType?{"Content-Type":contentType}:{})},body,signal:AbortSignal.timeout(90000)});if(!response.ok){const status=response.status;throw new ApiError(status===401?"OpenAI could not verify this API key. Check the key in Settings.":status===429?"OpenAI usage limit reached. Check your API credits or try again shortly.":status===403||status===404?"This API account does not have access to the requested model.":"OpenAI could not finish this request. Try again shortly.",status>=500?502:status);}return response.json() as Promise<Record<string,unknown>>;}
export function apiFailure(error:unknown){if(error instanceof ApiError)return Response.json({error:error.message},{status:error.status,headers:{"Cache-Control":"no-store"}});if(error instanceof z.ZodError)return Response.json({error:"The request or generated pattern was invalid. Your notebook has not been changed."},{status:422});if(error instanceof Error&&["TimeoutError","AbortError"].includes(error.name))return Response.json({error:"The request took too long. Your notebook is safe; try again."},{status:504});return Response.json({error:"The request could not be completed. Your notebook has not been changed."},{status:500});}
