export type Track={name:string;color:string;hits:boolean[];muted:boolean};
export type RecordingAnalysis={duration:number;onsets:number[];envelope:number[];hits:boolean[];sections:{start:number;end:number;label:string}[];origin:number;method:string};
export function makeDemo():Track[]{return [{name:"Part 1",color:"orange",hits:[true,false,true,false,false,true,false,true,false,true,false,false],muted:false},{name:"Part 2",color:"blue",hits:[false,false,false,true,false,false,true,false,true,false,false,true],muted:false},{name:"Pulse",color:"slate",hits:Array.from({length:12},(_,i)=>i%3===0),muted:false}];}
export function resizeTracks(tracks:Track[],steps:number){return tracks.map(t=>({...t,hits:Array.from({length:steps},(_,i)=>t.hits[i]??false)}));}
export function quantize(onsets:number[],bpm:number,steps:number){const origin=onsets[0]||0,pulse=60/bpm/3,hits=Array(steps).fill(false);for(const t of onsets){const ix=Math.round((t-origin)/pulse);if(ix>=0&&ix<steps)hits[ix]=true;}return hits;}
export function analyzeSamples(samples:Float32Array,sampleRate:number,bpm:number,steps:number,threshold=.018):RecordingAnalysis{
  const hop=Math.max(1,Math.floor(sampleRate*.01)),energy:number[]=[];
  for(let i=0;i<samples.length;i+=hop){let sum=0;const end=Math.min(i+hop,samples.length);for(let j=i;j<end;j++)sum+=samples[j]*samples[j];energy.push(Math.sqrt(sum/(end-i)));}
  const onsets:number[]=[];let last=-1;for(let i=1;i<energy.length-1;i++){const previous=energy.slice(Math.max(0,i-8),i),baseline=previous.reduce((a,b)=>a+b,0)/previous.length,time=i*hop/sampleRate;if(energy[i]>threshold&&energy[i]>baseline*1.9&&time-last>.09){onsets.push(time);last=time;}}
  const max=energy.reduce((a,b)=>Math.max(a,b),.001);const envelope=Array.from({length:100},(_,i)=>{const a=Math.floor(i*energy.length/100),b=Math.max(a+1,Math.floor((i+1)*energy.length/100));return Math.max(0,...energy.slice(a,b))/max;});
  const duration=samples.length/sampleRate,blocks:number[]=[],secondFrames=Math.max(1,Math.round(sampleRate/hop));for(let i=0;i<energy.length;i+=secondFrames){const values=energy.slice(i,i+secondFrames);blocks.push(values.reduce((a,b)=>a+b,0)/values.length);}
  const boundaries=[0];for(let i=2;i<blocks.length-1;i++){if(i-boundaries[boundaries.length-1]<2)continue;const a=blocks[i-1],b=blocks[i];if(Math.max(a,b)>.015&&Math.abs(b-a)/Math.max(a,b)>.6)boundaries.push(i);}boundaries.push(duration);
  return {duration,onsets,envelope,hits:quantize(onsets,bpm,steps),origin:onsets[0]||0,method:"RMS onset detection; first cycle quantized at researcher-selected tempo; no pitch or instrument classification",sections:boundaries.slice(0,-1).map((start,i)=>({start,end:boundaries[i+1],label:"Candidate section · review by listening"}))};
}
export function scheduleHit(ctx:BaseAudioContext,time:number,part:number){const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type=part%3===0?"triangle":"sine";oscillator.frequency.setValueAtTime(part%3===0?850:part%3===1?430:150,time);oscillator.frequency.exponentialRampToValueAtTime(part%3===2?55:part%3===0?260:300,time+.08);gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(part%3===2?.3:.2,time+.003);gain.gain.exponentialRampToValueAtTime(.0001,time+.13);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(time);oscillator.stop(time+.15);return oscillator;}
function xml(s:string){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");}
export function exportMusicXML(tracks:Track[],steps:number,bpm:number,title:string){return `<?xml version="1.0" encoding="utf-8"?>\n<score-partwise version="4.0"><work><work-title>${xml(title)}</work-title></work><part-list>${tracks.map((t,i)=>`<score-part id="P${i+1}"><part-name>${xml(t.name)}</part-name></score-part>`).join("")}</part-list>${tracks.map((t,i)=>`<part id="P${i+1}"><measure number="1"><attributes><divisions>2</divisions><time><beats>${steps}</beats><beat-type>8</beat-type></time><clef><sign>percussion</sign></clef></attributes><direction><direction-type><metronome><beat-unit>quarter</beat-unit><beat-unit-dot/><per-minute>${bpm}</per-minute></metronome></direction-type><sound tempo="${bpm*1.5}"/></direction>${t.hits.map(hit=>`<note>${hit?"<unpitched><display-step>C</display-step><display-octave>5</display-octave></unpitched>":"<rest/>"}<duration>1</duration><type>eighth</type></note>`).join("")}<barline location="right"><bar-style>light-heavy</bar-style></barline></measure></part>`).join("")}</score-partwise>`;}
export function scoreTaps(target:number[],taps:number[],tolerance:number){const available=[...taps];let matches=0,totalError=0;for(const time of [...target].sort((a,b)=>a-b)){let best=-1,distance=Infinity;available.forEach((v,i)=>{if(Math.abs(v-time)<distance){best=i;distance=Math.abs(v-time);}});if(best>=0&&distance<tolerance){matches++;totalError+=distance;available.splice(best,1);}}return {matches,extra:available.length,averageMs:matches?Math.round(totalError/matches*1000):0};}
